/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Material = {
  _id: string;
  _type: "material";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Subscribers = {
  _id: string;
  _type: "subscribers";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  createdAt?: string;
};

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  showOn?: "desktop" | "mobile" | "both";
  desktop?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    buttonTheme?: "light" | "dark";
  };
  mobile?: {
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    buttonTheme?: "light" | "dark";
  };
};

export type OrderItem = {
  _type: "orderItem";
  product?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "product";
  };
  variant?: {
    color?: string;
    variantKey?: string;
  };
  quantity?: number;
  price?: number;
  productName?: string;
  productImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
  customerName?: string;
  phone?: string;
  email?: string;
  address?: {
    district?: string;
    city?: string;
    line1?: string;
    notes?: string;
  };
  paymentMethod?: "COD" | "BANK";
  items?: Array<{
    _key: string;
  } & OrderItem>;
  subtotal?: number;
  shippingCost?: number;
  discountAmount?: number;
  total?: number;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  itemCode?: string;
  isPreOrder?: boolean;
  materials?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "material";
  }>;
  variants?: Array<{
    colorName?: string;
    openingStock?: number;
    stockOut?: number;
    images?: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    _type: "variant";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  status?: "new" | "hot" | "best";
  isFeatured?: boolean;
  features?: Array<{
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    label?: string;
    _key: string;
  }>;
  specifications?: Array<{
    icon?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    value?: string;
    _key: string;
  }>;
  realImages?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  realVideos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  deliveryCharges?: {
    colombo?: number;
    suburbs?: number;
    others?: number;
  };
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Material | Page | Subscribers | Banner | OrderItem | Order | Product | SanityFileAsset | Category | Slug | BlockContent | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Settings;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/query.ts
// Variable: BANNER_QUERY
// Query: *[_type == "banner"]{  showOn,  desktop { image { asset }, buttonTheme },  mobile { image { asset }, buttonTheme }}
export type BANNER_QUERYResult = Array<{
  showOn: "both" | "desktop" | "mobile" | null;
  desktop: {
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
    buttonTheme: "dark" | "light" | null;
  } | null;
  mobile: {
    image: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
    buttonTheme: "dark" | "light" | null;
  } | null;
}>;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  title,  content}
export type PAGE_QUERYResult = {
  title: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: SHIPPING_QUERY
// Query: *[_type == "settings"][0]{  deliveryCharges {    colombo,    suburbs,    others  }}
export type SHIPPING_QUERYResult = {
  deliveryCharges: {
    colombo: number | null;
    suburbs: number | null;
    others: number | null;
  } | null;
} | null;
// Variable: FEATURED_CATEGORY_QUERY
// Query: *[_type == 'category' && featured == true] | order(name desc) {    _id,    name,    slug,    image { asset }  }
export type FEATURED_CATEGORY_QUERYResult = Array<never>;
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type=="product"] | order(name asc){    _id,    name,    slug,    price,    discount,    status,    isPreOrder,    isFeatured,    materials[]->{ _id, name, slug },    categories[]->{      title    },    variants[]{      _key,      colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] { _key, asset }    }  }
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  status: "best" | "hot" | "new" | null;
  isPreOrder: boolean | null;
  isFeatured: boolean | null;
  materials: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
  categories: Array<{
    title: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    openingStock: number | null;
    stockOut: number | null;
    availableStock: number | null;
    images: Array<{
      _key: string;
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    }> | null;
  }> | null;
}>;
// Variable: HOT_PRODUCTS_QUERY
// Query: *[_type == 'product' && status == 'hot'] | order(name asc){    _id,    name,    slug,    price,    discount,    isPreOrder,    materials[]->{ _id, name, slug },    categories[]->{      title    },    variants[]{      _key,      colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] { _key, asset }    }  }
export type HOT_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  isPreOrder: boolean | null;
  materials: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
  categories: Array<{
    title: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    openingStock: number | null;
    stockOut: number | null;
    availableStock: number | null;
    images: Array<{
      _key: string;
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    }> | null;
  }> | null;
}>;
// Variable: DEAL_PRODUCTS_QUERY
// Query: *[_type == 'product' && status == 'sale'] | order(name asc){    _id,    name,    slug,    price,    discount,    isPreOrder,    materials[]->{ _id, name, slug },    categories[]->{      title    },    variants[]{      _key,      colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] { _key, asset }    }  }
export type DEAL_PRODUCTS_QUERYResult = Array<never>;
// Variable: NEW_PRODUCTS_QUERY
// Query: *[_type == 'product' && status == 'new'] | order(name asc){    _id,    name,    slug,    price,    discount,    isPreOrder,    materials[]->{ _id, name, slug },    categories[]->{      title    },    variants[]{      _key,      colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] { _key, asset }    }  }
export type NEW_PRODUCTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  isPreOrder: boolean | null;
  materials: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
  categories: Array<{
    title: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    openingStock: number | null;
    stockOut: number | null;
    availableStock: number | null;
    images: Array<{
      _key: string;
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    }> | null;
  }> | null;
}>;
// Variable: FEATURE_PRODUCTS
// Query: *[_type == 'product' && isFeatured == true] | order(name asc){    _id,    name,    slug,    price,    discount,    status,    isPreOrder,    materials[]->{ _id, name, slug },    categories[]->{      title    },    variants[]{      _key,      colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] { _key, asset }    }  }
export type FEATURE_PRODUCTSResult = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  price: number | null;
  discount: number | null;
  status: "best" | "hot" | "new" | null;
  isPreOrder: boolean | null;
  materials: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
  categories: Array<{
    title: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    openingStock: number | null;
    stockOut: number | null;
    availableStock: number | null;
    images: Array<{
      _key: string;
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    }> | null;
  }> | null;
}>;
// Variable: ADDRESS_QUERY
// Query: *[_type=="address"] | order(publishedAt desc) {    _id,    location,    address,    phone,    email  }
export type ADDRESS_QUERYResult = Array<never>;
// Variable: ALL_MATERIALS_QUERY
// Query: *[_type == "material"] | order(name asc) {    _id,    name,    "slug": slug.current  }
export type ALL_MATERIALS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
}>;
// Variable: ALLCATEGORIES_QUERY
// Query: *[_type == 'category'] | order(name asc)[0...$quantity] {    _id,    name,    slug,    image { asset }  }
export type ALLCATEGORIES_QUERYResult = Array<{
  _id: string;
  name: null;
  slug: Slug | null;
  image: {
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
  } | null;
}>;
// Variable: SUBSCRIBERS_QUERY
// Query: *[_type == "subscribers"]{  _id,  email,  createdAt} | order(createdAt desc)
export type SUBSCRIBERS_QUERYResult = Array<{
  _id: string;
  email: string | null;
  createdAt: string | null;
}>;
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    _id,    name,    slug,    description,    price,    discount,    status,    isFeatured,    isPreOrder,    materials[]->{ _id, name, slug },    categories[]->{      _id,      title    },    variants[] {      _key,        colorName,      openingStock,      stockOut,      "availableStock": openingStock - coalesce(stockOut, 0),      images[] {        _key,        asset      }    },    features[] {      _key,      label,      icon { asset }    },    specifications[] {      _key,      value,      icon { asset }    },    realImages[] {      _key,      asset    },    realVideos[] {      _key,      asset->{url} // <-- This is OK, <video> just needs the url string    }  }
export type PRODUCT_BY_SLUG_QUERYResult = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  status: "best" | "hot" | "new" | null;
  isFeatured: boolean | null;
  isPreOrder: boolean | null;
  materials: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    colorName: string | null;
    openingStock: number | null;
    stockOut: number | null;
    availableStock: number | null;
    images: Array<{
      _key: string;
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    }> | null;
  }> | null;
  features: Array<{
    _key: string;
    label: string | null;
    icon: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  }> | null;
  specifications: Array<{
    _key: string;
    value: string | null;
    icon: {
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  }> | null;
  realImages: Array<{
    _key: string;
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
  }> | null;
  realVideos: Array<{
    _key: string;
    asset: {
      url: string | null;
    } | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"banner\"]{\n  showOn,\n  desktop { image { asset }, buttonTheme },\n  mobile { image { asset }, buttonTheme }\n}": BANNER_QUERYResult;
    "*[_type == \"page\" && slug.current == $slug][0]{\n  title,\n  content\n}": PAGE_QUERYResult;
    "*[_type == \"settings\"][0]{\n  deliveryCharges {\n    colombo,\n    suburbs,\n    others\n  }\n}": SHIPPING_QUERYResult;
    "*[_type == 'category' && featured == true] | order(name desc) {\n    _id,\n    name,\n    slug,\n    image { asset }\n  }": FEATURED_CATEGORY_QUERYResult;
    "\n  *[_type==\"product\"] | order(name asc){\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    status,\n    isPreOrder,\n    isFeatured,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      title\n    },\n    variants[]{\n      _key,\n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] { _key, asset }\n    }\n  }\n": ALL_PRODUCTS_QUERYResult;
    "\n  *[_type == 'product' && status == 'hot'] | order(name asc){\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    isPreOrder,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      title\n    },\n    variants[]{\n      _key,\n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] { _key, asset }\n    }\n  }\n": HOT_PRODUCTS_QUERYResult;
    "\n  *[_type == 'product' && status == 'sale'] | order(name asc){\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    isPreOrder,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      title\n    },\n    variants[]{\n      _key,\n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] { _key, asset }\n    }\n  }\n": DEAL_PRODUCTS_QUERYResult;
    "\n  *[_type == 'product' && status == 'new'] | order(name asc){\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    isPreOrder,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      title\n    },\n    variants[]{\n      _key,\n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] { _key, asset }\n    }\n  }\n": NEW_PRODUCTS_QUERYResult;
    "\n  *[_type == 'product' && isFeatured == true] | order(name asc){\n    _id,\n    name,\n    slug,\n    price,\n    discount,\n    status,\n    isPreOrder,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      title\n    },\n    variants[]{\n      _key,\n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] { _key, asset }\n    }\n  }\n": FEATURE_PRODUCTSResult;
    "*[_type==\"address\"] | order(publishedAt desc) {\n    _id,\n    location,\n    address,\n    phone,\n    email\n  }": ADDRESS_QUERYResult;
    "*[_type == \"material\"] | order(name asc) {\n    _id,\n    name,\n    \"slug\": slug.current\n  }": ALL_MATERIALS_QUERYResult;
    "*[_type == 'category'] | order(name asc)[0...$quantity] {\n    _id,\n    name,\n    slug,\n    image { asset }\n  }": ALLCATEGORIES_QUERYResult;
    "*[_type == \"subscribers\"]{\n  _id,\n  email,\n  createdAt\n} | order(createdAt desc)": SUBSCRIBERS_QUERYResult;
    "\n  *[_type == \"product\" && slug.current == $slug][0]{\n    _id,\n    name,\n    slug,\n    description,\n    price,\n    discount,\n    status,\n    isFeatured,\n    isPreOrder,\n    materials[]->{ _id, name, slug },\n    categories[]->{\n      _id,\n      title\n    },\n    variants[] {\n      _key,  \n      colorName,\n      openingStock,\n      stockOut,\n      \"availableStock\": openingStock - coalesce(stockOut, 0),\n      images[] {\n        _key,\n        asset\n      }\n    },\n    features[] {\n      _key,\n      label,\n      icon { asset }\n    },\n    specifications[] {\n      _key,\n      value,\n      icon { asset }\n    },\n    realImages[] {\n      _key,\n      asset\n    },\n    realVideos[] {\n      _key,\n      asset->{url} // <-- This is OK, <video> just needs the url string\n    }\n  }\n": PRODUCT_BY_SLUG_QUERYResult;
  }
}
